### ISSUE TITLE
-Y Preserves the input surface mesh (does not modify it).

### ISSUE THREAD

**Issue by hearables-pkinsella** [pyvista/tetgen#13]
How can I mimic the -Y function so it does not modify the input surface? I have tried setting the quality, nobisect and steinerleft to 0 but it still adds 664 steiner points

**Comment by akaszynski** [comment]
You should be able to add switches directly.  Have you tried that with the cython version of the module?

**Comment by hearables-pkinsella** [comment]
I haven't tried that yet, do you have a short example of how I would do that?

**Comment by hearables-pkinsella** [comment]
Sorry got it working, thanks for your help.

switches = b'-Y'
node,elem = _tetgen.Tetrahedralize(V,F,switches)

**Comment by akaszynski** [comment]
Thanks!

**Comment by akaszynski** [comment]
I'm adding in the switches feature to the python tetgen class.  Release should be out shortly.
