### ISSUE TITLE
Creating and writing mesh files

### ISSUE THREAD

**Issue by steersteer** [pyvista/tetgen#14]
Hi,
I have two questions. 
How might I go about writing the meshes to file? I can't seem to find a method.

My second question is regarding tetrahedral meshes. 
I have segmented some bone samples and now have two 3D numpy arrays with the shape (10, 964, 1754) though the "10" changes depending on how many slices I process at a time. Each array contains images such as:
![trabecular_mask_1](https://user-images.githubusercontent.com/60923319/75117520-08a87000-566a-11ea-9bbf-93f5142ae923.png)
![cortical_mask_7](https://user-images.githubusercontent.com/60923319/75117521-09410680-566a-11ea-9796-bb38f24efec8.png)

I'd like to create tetrahedral volume meshes of each for the purpose of FE analysis.
So far I have used marching cubes and various meshing modules and have only managed to create triangle meshes which seem to only be a "shell" of my total shape. Is it possible to create a full tet mesh of my shapes?

**Comment by banesullivan** [comment]
I can easily answer your first question:

> How might I go about writing the meshes to file? I can't seem to find a method.

You must use the underlying PyVista mesh object and either it's `.save()` method to save it ot a VTK file or `pyvista.save_meshio()` to save the mesh in a meshio file format

This PyVista mesh is under the `grid` attribute of the `tetgen.TetGen` object you use.

To save, follow: https://docs.pyvista.org/getting-started/simple.html#exporting

**Comment by banesullivan** [comment]
As for your second question, can you provide this (or sample) data?

**Comment by steersteer** [comment]
I've been going round and round in circles with this so I'm getting quite confused now!
So I tried this: 
`T_verts, T_faces, T_normals, T_values = marching_cubes_lewiner(all_trabecular_slices, 0, spacing=(1.0, 1.0, 1.0), step_size=stepsizetrab) `

`tet = tetgen.TetGen(W_verts,W_faces)`

`tet.save("tet.vtk") `

And I get the error "AttributeError: 'TetGen' object has no attribute 'save'". I'm sure I'm doing something wrong.
Using pyvista.save_meshio() results in "AttributeError: 'TetGen' object has no attribute 'cast_to_unstructured_grid'"

Adding `tet.tetrahedralize(order=1, mindihedral=20, minratio=1.5)` after the `tet = tetgen.TetGen(W_verts,W_faces)` line results in "Exception: Failed to tetrahedralize.
May need to repair surface by making it manifold: Unknown exception"
I assumed I'd need this to tetrahedralise the mesh but I have no idea any more.

I've attached a sample of 20 of the images I wanted to conduct FE analysis on as a solid object







[Trabecular_Mask.zip](https://github.com/pyvista/tetgen/files/4242290/Trabecular_Mask.zip)

**Comment by banesullivan** [comment]
**This PyVista mesh is under the `grid` attribute of the `tetgen.TetGen` object you use.**

**Comment by banesullivan** [comment]
**This PyVista mesh is under the `grid` attribute of the `tetgen.TetGen` object you use.**

```py
tet = tetgen.TetGen(T_verts,T_faces)
tet.make_manifold()
tet.tetrahedralize()

grid = tet.grid
grid.save("tet.vtk")
grid.plot()
```

**Comment by banesullivan** [comment]
@steersteer, if you're able to reshare the data here, I'd be happy to try to solve this unique problem

**Comment by steersteer** [comment]
Ok thanks, I did actually finally figure it out but didn't have time to update. I didn't know about the make_manifold function, I had been using pymeshfix for that, hopefully this will be quicker. Thanks for your help!
