### ISSUE TITLE
Tetrahedralize seems to remove internal volumes

### ISSUE THREAD

**Issue by heidtn** [pyvista/tetgen#15]
I have a mesh with internal volumes (i.e. voids) and tetrahedralize seems to remove these volumes leaving only the outer mesh.  Is there a way to preserve these volumes?

**Comment by akaszynski** [comment]
I'm not sure if this is a limitation with the core `meshfix` code.  Is the mesh already manifold before you start the tetrahedralization?

**Comment by heidtn** [comment]
I believe so, I'm using the trimesh library to manage the meshes which provides an is_watertight function (every edge is included in two faces).  This evaluates to true, so it should imply the mesh is manifold.  I'll try writing a function to evaluate manifold as well.

Is there a way to disable the meshfix code to test?

**Comment by akaszynski** [comment]
Yes, but you'll have to use the underlying cython library.  Use that instead of the tetgen wrapper.  It's detailed in the docs.

**Comment by heidtn** [comment]
I think I may have finally figured out what is happening.  The vertices for the internal volumes are preserved, but the volumes themselves are filled with tetrahedra instead of remaining empty.  I'm not sure if this is intended behavior or not.  If it is, feel free to close this issue.

Below is an example for reproducing:
```python   
    import trimesh
    bigcube = trimesh.creation.box((1, 1, 1))
    smallcube = trimesh.creation.box((0.5, 0.5, 0.5))
    diff = trimesh.boolean.difference((bigcube, smallcube))
    new_verts = diff.vertices
    new_faces = diff.faces

    tet = tetgen.TetGen(new_verts, new_faces)
    tet.tetrahedralize(order=1, mindihedral=20, minratio=1.5)
```

**Comment by akaszynski** [comment]
I think it's an expected "feature" as tetgen expects a manifold surface and I'm assuming that it will always mesh the internal volume unless it's "open".

**Comment by m-ring** [comment]
I found a workaround where you generate a mesh for the whole part with inner voids and a second mesh just for the inner void. You generate the grid for the complete mesh and filter all cells which are inside the mesh for the void(s). The second mesh, however, had to be made with _pyvista_ as I couldn't get it to work with the _trimesh_-mesh . Maybe there is a better way, but I think the main point is shown.
The code below is based on the example of _tetgen_, but I am sure you will notice. :)

```
import numpy as np
import pyvista as pv
import tetgen
import trimesh

# GENERATE MESH FOR COMPLETE PART ####################################
sphere1 = trimesh.creation.icosphere(radius=1.0)
sphere2 = trimesh.creation.icosphere(radius=0.5)
diff = trimesh.boolean.difference((sphere1, sphere2))
new_verts = diff.vertices
new_faces = diff.faces

# GENERATE MESH FOR VOIDS ############################################
mesh_voids = pv.Sphere(radius=0.5)

# TETRAHEDRALIZE MESH AND GENERATE GRID ##############################
tet = tetgen.TetGen(new_verts, new_faces)
nodes, elements = tet.tetrahedralize(order=1, mindihedral=20, minratio=1.5)
grid = tet.grid

# FILTER OUT ALL CELLS INSIDE MESH OF VOIDS ##########################
# Center of cells
cells = grid.cells.reshape(-1, 5)[:, 1:]
cell_center = grid.points[cells].mean(1)
# finde cells inside mesh
points_poly = pv.PolyData(cell_center)
mask = points_poly.select_enclosed_points(mesh_voids)['SelectedPoints']
# invert mask to find all cells outside voids
mask = np.logical_not(mask)
# filter cells
cell_ind = mask.nonzero()[0]
grid = grid.extract_cells(cell_ind)

# CUT GRID IN HALF TO SHOW VOID ######################################
# Center of cells
cells = grid.cells.reshape(-1, 5)[:, 1:]
cell_center = grid.points[cells].mean(1)
# FILTER CELLS
mask = cell_center[:, 2] < 0
cell_ind = mask.nonzero()[0]
grid = grid.extract_cells(cell_ind)

# PLOT GRID #########################################################
plotter = pv.Plotter()
plotter.add_mesh(grid, 'lightgrey', lighting=True, show_edges=True)
plotter.show()
```
