### ISSUE TITLE
Add AGPL guidelines for usage

### ISSUE THREAD

**Issue by banesullivan** [pyvista/tetgen#34]
AGPL is a complicated and widely (mis-?)interpreted license. We should add a section of the README to make sure people realize this software is under an AGPL license (much the same as the C++ TetGen source) and add a few of our interpretations/notes.

Some things to note:

- Simply importing this package into a new package might require adopting the AGPL license (e.g., `import tetgen`)
- Including this in your dependencies (e.g., `requirements.txt` or `setup.py`) should not require adopting the AGPL license

@jokva, if you have some time, I would greatly appreciate any guidance you may be able to provide here

**Comment by banesullivan** [comment]
Perhaps we can give some examples of usage where you do and do not need to adopt AGPL

**Comment by jokva** [comment]
I'm not sure if this is the place to do it, especially since it's easy to get wrong. I would say just stating it clearly in the readme (or other landing page docs) and linking to the FSF and/or other references should be fine.
