### ISSUE TITLE
Internalerror in findedge() TetGen Problem

### ISSUE THREAD

**Issue by Lorenzomarta** [pyvista/tetgen#36]
Hello everyone,
I’m having trouble using the command “vmtkmeshgenerator” to obtain internal tetrahedral mesh, in particular starting with this command:

vmtk vmtkmeshgenerator -ifile sup3.vtp -skipremeshing 1 -volumeelementfactor 1 -ofile mesh.vtu

I obtain the following output:

```
[...]
Duplicating background mesh.
Internalerror in findedge():  Unable to find an edge in subface.
ERROR: In ../vtkVmtk/Misc/vtkvmtkTetGenWrapper.cxx, line 431
vtkvmtkTetGenWrapper (0x7fa3b27ef170): TetGen quit with an exception.
[...]

```

What do you suggest me to do?
Thanks in advance.

**Comment by banesullivan** [comment]
vtmk is totally different from this software and it is not using any of the code here (AFAIK). I'd recommend opening an issue with vmtk: https://github.com/vmtk/vmtk
