### ISSUE TITLE
Does tetgen do mesh refinement ?

### ISSUE THREAD

**Issue by gabrielfougeron** [pyvista/tetgen#47]
Hi,

I have an existing (small-ish) tetrahedral mesh, and I want to refine it. Nothing super fancy, no adaptive refinement. Uniform refinement would be perfect. Is there a way to achieve this using tetgen ?

If no, do you know of another open source alternative ?

Thank you very much,

**Comment by banesullivan** [comment]
I'm not sure if tetgen has a mechanism for that, but PyVista does: `subdivide_tetra`: https://docs.pyvista.org/api/core/_autosummary/pyvista.UnstructuredGridFilters.subdivide_tetra.html#subdivide-tetra

**Comment by gabrielfougeron** [comment]
Awesome, thank you! I'll check it out.
