### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by YMX2022** [pyvista/tetgen#50]
Great work!
However, some error occurred when I call "import tetgen"

from pyvista._vtk import VTK9
ImportError: cannot import name 'VTK9' from 'pyvista._vtk'

Do you have any suggestions on the error?

**Comment by banesullivan** [comment]
This package needs to be updated to work with the latest version of PyVista. PyVista dropped VTK8 support and this module might still be trying to support VTK8. 

Downgrading PyVista should work for now:

```
pip install 'pyvista<0.39'
```

**Comment by akaszynski** [comment]
I'll patch and release. Had to change https://github.com/pyansys/pymapdl-reader as well.
