### ISSUE TITLE
readme usage example is missing code

### ISSUE THREAD

**Issue by sfladi** [pyvista/tetgen#67]
The function `write_background_mesh()` in the README.md is missing code to write `background_mesh` and  `mtr_content` to the mentioned .b.node- , .b.ele- and .b.mtr-files

https://github.com/pyvista/tetgen/blob/c3cb5fd4320d643aa82c5c8a32c7dfa85517f02e/README.rst?plain=1#L193-L204

**Comment by akaszynski** [comment]
Resolved in #69
